#!/bin/bash

set -e

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

[ -d $SNAP_COMMON/config ] && [ -e $SNAP_COMMON/config/flask_secrets ] && export FLASK_SECRETS=$SNAP_COMMON/config/flask_secrets

mkdir -p $SNAP_COMMON/flask-app
chmod -R 777 $SNAP_COMMON/flask-app 

exec "$SNAP/bin/gunicorn" --chdir "$SNAP/flask-app" --bind "unix:$SNAP_COMMON/flask-app/flask-app.sock" application:app "$@"
