name: flask-nginx
version: '0.1' 
summary: flask-nginx
description: |
  flask-nginx

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  flask-nginx:
    command: wrappers/flask-nginx
    daemon: simple
    plugs: [network, network-bind]
  nginx:
    command: wrappers/nginx-wrap
    daemon: simple
    plugs: [network, network-bind]


parts:
  flask-nginx:
    plugin: python
    source: https://github.com/jamesbeedy/flask-example.git
    source-type: git
    python-version: python3
    requirements: requirements.txt
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/
  wrappers:
    plugin: dump
    source: snap/
  nginx:
    plugin: nginx
    source: .
    install: |
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
      rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
      cp ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
